name: Actionlint

on:
  workflow_call:

jobs:
  actionlint:
    name: Workflow Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install and run actionlint
        run: |
          bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
