name: Dead Code

on:
  workflow_call:

jobs:
  knip:
    name: Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - run: npm run quality:dead-code
